config/routes.rb
Rails.application.routes.draw do
  
resources :transactions

root to: "transactions#index"

end

app/models/material.rb
class Material < ActiveRecord::Base
	belongs_to :Transaction

	validates :name, presence: true
	
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
	has_many :users

	validates :tax_receipt, presence: true
  
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :transactions

	validates :name, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

	def index
		@transactions = Transaction.all
	
	end

	def show
		@transaction = Transaction.find_by(id: params["id"])
		@material = Material.find_by(id: @transaction.material_id)
		@buyer = User.find_by(id: @transaction.buyer_user_id)
		@seller = User.find_by(id: @transaction.seller_user_id)
	end	 

	def new
    @transaction = Transaction.new
  end

  def create
		transaction_params= params.require(:transaction).permit(:tax_receipt)
			# have to be long because of security
		Transaction.create(transaction_params)
  	redirect_to transaction_path
  end	

  def edit
  	@transaction=Transaction.find_by(id: params["id"])
  end

  def update
  	transaction_params= params.require(:transaction).permit(:tax_receipt)
		@transaction=Transaction.find_by(id: params["id"])
		@transaction.update(transaction_params)
		redirect_to transaction_path 	
  end

  def destroy
  	@transaction=Transaction.find_by(id: params["id"])
  	@transaction.destroy
  	redirect_to trasanction_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Transactions</title>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class ="container">
		<%= yield %>
	</div>
		
</body>
</html>

app/views/transactions/edit.html.erb
<%= form_for @transaction do |form| %>
  <div class="form-group">
    <%= form.label :tax_receipt %>
    <%= form.text_field :tax_receipt, class: "form-control" %>
  </div>
  <%= form.button 'Update transaction', class: "btn btn-success" %>
<% end %>

app/views/transactions/index.html.erb
<h1> Transactions </h1>

<p><a href= "/transactions/new" class="btn btn-primary"> New transaction </a> </p>

<% @transactions.each do |transaction| %>
	<li>
	<a href="/transactions/<%=transaction.id%>"> <%= transaction.tax_receipt %></a>
	<%= link_to "edit", edit_transaction_path(transaction) %>
    <%= link_to "delete", transaction_path(transaction), method: :delete %>
    </li>

<% end %>

app/views/transactions/new.html.erb
<!--  
<form action="/transactions" method="POST">


  <div class="form-group">
    <label for="name">Type the tax receipt</label>
    <input type="text" class="form-control" id="tax_receipt" placeholder="Enter the tax_receipt number">
  </div>

</form>
-->

<%= form_for @transaction do |form| %>
  <div class="form-group">
    <%= form.label :tax_receipt %>
    <%= form.text_field :tax_receipt, class: "form-control" %>
  </div>
  <%= form.button 'Create transaction', class: "btn btn-success" %>
<% end %>

app/views/transactions/show.html.erb
<h1>
	Transaction Receipt #
	<%= @transaction.tax_receipt %>
</h1>

<h3>

This website certificates that
<%= @buyer.name %> 
has bought from 
<%= @seller.name%> 
<%= @transaction.tonnage %>kg of 
<%= @material.name %>
for
$<%= @transaction.price %>/kg

</h3>	